- name: load current .bashrc
  shell: "cat ~/.bashrc"
  register: bashrcContent
  changed_when: false

- name: set export path for Sublime
  shell: "echo 'export PATH=$PATH:/home/christian/Sublime\ Text\ 2' >> ~/.bashrc"
  when: not bashrcContent.stdout | search("export PATH=\$PATH:/home/christian/Sublime Text 2") #"